<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // async函数返回一个 Promise 对象，可以使用then方法添加回调函数。
        // 当函数执行的时候，一旦遇到await就会先返回，等到异步操作完成，
        // 再接着执行函数体内后面的语句。

        // 指定多少毫秒后输出一个值
        function timeout(ms) {
            return new Promise((resolve) => {
                setTimeout(resolve, ms);
            });
        }

        async function asyncPrint(value, ms) {
            await timeout(ms);
            console.log(value);
        }

        asyncPrint('hello world', 50);

        // async函数返回一个 Promise 对象。
            // async函数内部return语句返回的值，会成为then方法回调函数的参数。
            async function f() {
            return 'hello world';
            }

            f().then(v => console.log(v))
            // "hello world"

            // 如果await后面的异步操作出错，那么等同于async函数返回的 Promise 对象被reject。
            async function f() {
                 await new Promise(function (resolve, reject) {
                 throw new Error('出错了');
                  });
            }
            f()
            .then(v => console.log(v))
            .catch(e => console.log(e))
            // Error：出错了


// await命令后面的Promise对象，运行结果可能是rejected，
// 所以最好把await命令放在try...catch代码块中。
            async function main() {
            try {
                const val1 = await firstStep();
                const val2 = await secondStep(val1);
                const val3 = await thirdStep(val1, val2);
            
                console.log('Final: ', val3);
            }
            catch (err) {
                console.error(err);
            }
            }
    </script>
</body>
</html>